# Regression Week 5: LASSO (coordinate descent)

In this notebook, you will implement your very own LASSO solver via coordinate descent. You will:
* Write a function to normalize features
* Implement coordinate descent for LASSO
* Explore effects of L1 penalty

# Fire up graphlab create

Make sure you have the latest version of graphlab (>= 1.7)

In [56]:
import graphlab
import numpy as np 
from math import sqrt
ctscan = graphlab.SFrame.read_csv("C:\Third Sem\Machine Learning\Assignment_2\datasets\slice_localization_data1.csv", header=True)

Finished parsing file C:\Third Sem\Machine Learning\Assignment_2\datasets\slice_localization_data1.csv

Parsing completed. Parsed 100 lines in 0.915425 secs.

------------------------------------------------------
Inferred types from first 100 line(s) of file as 
column_type_hints=[long,long,long,long,long,long,long,float,float,float,float,float,float,float,float,float,long,long,float,float,float,float,float,float,float,float,float,float,long,long,float,float,float,float,float,float,float,float,long,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,long,long,float,float,float,float,long,long,float,float,float,long,float,float,float,float,long,long,long,float,float,float,float,float,float,float,float,float,float,float,float,long,long,long,float,float,float,float,float,float,float,float,long,long,float,float,float,float,float,float,float,float,float,float,long,float,float,float,float,float,float,float,float,float,float,float,float,float,float,fl

Read 34336 lines. Lines per second: 20903.8

Finished parsing file C:\Third Sem\Machine Learning\Assignment_2\datasets\slice_localization_data1.csv

Parsing completed. Parsed 53500 lines in 2.08245 secs.

# Load in house sales data

Dataset is from house sales in King County, the region where the city of Seattle, WA is located.

If we want to do any "feature engineering" like creating new features or adjusting existing ones we should do this directly using the SFrames as seen in the first notebook of Week 2. For this notebook, however, we will work with the existing features.

# Import useful functions from previous notebook

As in Week 2, we convert the SFrame into a 2D Numpy array. Copy and paste `get_num_data()` from the second notebook of Week 2.

In [57]:
import numpy as np # note this allows us to refer to numpy as np instead 

In [58]:
def predict_output(feature_matrix, weights):
    # assume feature_matrix is a numpy matrix containing the features as columns and weights is a corresponding numpy array
    
    # create the predictions vector by using np.dot()
    predictions = np.dot(feature_matrix, weights)

    return(predictions)

Also, copy and paste the `predict_output()` function to compute the predictions for an entire matrix of features given the matrix and the weights:

# Normalize features
In the house dataset, features vary wildly in their relative magnitude: `sqft_living` is very large overall compared to `bedrooms`, for instance. As a result, weight for `sqft_living` would be much smaller than weight for `bedrooms`. This is problematic because "small" weights are dropped first as `l1_penalty` goes up. 

To give equal considerations for all features, we need to **normalize features** as discussed in the lectures: we divide each feature by its 2-norm so that the transformed feature has norm 1.

Let's see how we can do this normalization easily with Numpy: let us first consider a small matrix.

In [17]:
X = np.array([[3.,5.,8.],[4.,12.,15.]])
print X

[[  3.   5.   8.]
 [  4.  12.  15.]]


Numpy provides a shorthand for computing 2-norms of each column:

In [18]:
norms = np.linalg.norm(X, axis=0) # gives [norm(X[:,0]), norm(X[:,1]), norm(X[:,2])]
print norms

[  5.  13.  17.]


To normalize, apply element-wise division:

In [19]:
print X / norms # gives [X[:,0]/norm(X[:,0]), X[:,1]/norm(X[:,1]), X[:,2]/norm(X[:,2])]

[[ 0.6         0.38461538  0.47058824]
 [ 0.8         0.92307692  0.88235294]]


Using the shorthand we just covered, write a short function called `normalize_features(feature_matrix)`, which normalizes columns of a given feature matrix. The function should return a pair `(normalized_features, norms)`, where the second item contains the norms of original features. As discussed in the lectures, we will use these norms to normalize the test data in the same way as we normalized the training data. 

In [59]:
def normalize_features(feature_matrix):
    norms=np.linalg.norm(feature_matrix,axis=0)
    normalized_features=feature_matrix/norms
    return (normalized_features,norms)

To test the function, run the following:

In [61]:
features, norms = normalize_features(np.array([[3.,6.,9.],[4.,8.,12.]]))
print features
# should print
# [[ 0.6  0.6  0.6]
#  [ 0.8  0.8  0.8]]
print norms
# should print
# [5.  10.  15.]

[[ 0.6  0.6  0.6]
 [ 0.8  0.8  0.8]]
[  5.  10.  15.]


In [62]:
def get_numpy_data(data_sframe, features, output):
    data_sframe['constant'] = 1 # this is how you add a constant column to an SFrame
    # add the column 'constant' to the front of the features list so that we can extract it along with the others:
    features = ['constant'] + features # this is how you combine two lists
    # select the columns of data_SFrame given by the features list into the SFrame features_sframe (now including constant):
    features_sframe=data_sframe[features]
    # the following line will convert the features_SFrame into a numpy matrix:
    feature_matrix = features_sframe.to_numpy()
    # assign the column of data_sframe associated with the output to the SArray output_sarray
    #output_sarray=data_sframe['price']
    output_sarray=data_sframe[output]

    # the following will convert the SArray into a numpy array by first converting it to a list
    output_array = output_sarray.to_numpy()
    return(feature_matrix, output_array)

# Implementing Coordinate Descent with normalized features

We seek to obtain a sparse set of weights by minimizing the LASSO cost function
```
SUM[ (prediction - output)^2 ] + lambda*( |w[1]| + ... + |w[k]|).
```
(By convention, we do not include `w[0]` in the L1 penalty term. We never want to push the intercept to zero.)

The absolute value sign makes the cost function non-differentiable, so simple gradient descent is not viable (you would need to implement a method called subgradient descent). Instead, we will use **coordinate descent**: at each iteration, we will fix all weights but weight `i` and find the value of weight `i` that minimizes the objective. That is, we look for
```
argmin_{w[i]} [ SUM[ (prediction - output)^2 ] + lambda*( |w[1]| + ... + |w[k]|) ]
```
where all weights other than `w[i]` are held to be constant. We will optimize one `w[i]` at a time, circling through the weights multiple times.  
  1. Pick a coordinate `i`
  2. Compute `w[i]` that minimizes the cost function `SUM[ (prediction - output)^2 ] + lambda*( |w[1]| + ... + |w[k]|)`
  3. Repeat Steps 1 and 2 for all coordinates, multiple times

For this notebook, we use **cyclical coordinate descent with normalized features**, where we cycle through coordinates 0 to (d-1) in order, and assume the features were normalized as discussed above. The formula for optimizing each coordinate is as follows:
```
       ┌ (ro[i] + lambda/2)     if ro[i] < -lambda/2
w[i] = ├ 0                      if -lambda/2 <= ro[i] <= lambda/2
       └ (ro[i] - lambda/2)     if ro[i] > lambda/2
```
where
```
ro[i] = SUM[ [feature_i]*(output - prediction + w[i]*[feature_i]) ].
```

Note that we do not regularize the weight of the constant feature (intercept) `w[0]`, so, for this weight, the update is simply:
```
w[0] = ro[i]
```

## Effect of L1 penalty

Let us consider a simple model with 2 features:

In [63]:
simple_features = ['sqft_living', 'bedrooms']
my_output = 'price'
(simple_feature_matrix, output) = get_numpy_data(sales, simple_features, my_output)

NameError: name 'sales' is not defined

Don't forget to normalize features:

In [24]:
simple_feature_matrix, norms = normalize_features(simple_feature_matrix)

We assign some random set of initial weights and inspect the values of `ro[i]`:

In [25]:
weights = np.array([1., 4., 1.])

Use `predict_output()` to make predictions on this data.

In [26]:
prediction = predict_output(simple_feature_matrix,weights)
prediction

array([ 0.02675867,  0.04339256,  0.01990703, ...,  0.02289873,
        0.03178473,  0.02289873])

In [27]:
ro = np.zeros(simple_feature_matrix.shape[1])
ro

array([ 0.,  0.,  0.])

Compute the values of `ro[i]` for each feature in this simple model, using the formula given above, using the formula:
```
ro[i] = SUM[ [feature_i]*(output - prediction + w[i]*[feature_i]) ]
```

*Hint: You can get a Numpy vector for feature_i using:*
```
simple_feature_matrix[:,i]
```

In [28]:

for i in range(0,simple_feature_matrix.shape[1]):
    ro[i]= sum(simple_feature_matrix[:,i]*(output-prediction + (weights[i]*simple_feature_matrix[:,i])))
print ro

[ 79400300.03492953  87939470.77299079  80966698.67596525]


***QUIZ QUESTION***

Recall that, whenever `ro[i]` falls between `-l1_penalty/2` and `l1_penalty/2`, the corresponding weight `w[i]` is sent to zero. Now suppose we were to take one step of coordinate descent on either feature 1 or feature 2. What range of values of `l1_penalty` **would not** set `w[1]` zero, but **would** set `w[2]` to zero, if we were to take a step in that coordinate? 

In [29]:
diff = abs((ro[1]*2) - (ro[2]*2))

***QUIZ QUESTION***

What range of values of `l1_penalty` would set **both** `w[1]` and `w[2]` to zero, if we were to take a step in that coordinate? 

In [30]:
print ro[1]*2
print ro[2]*2

175878941.546
161933397.352


So we can say that `ro[i]` quantifies the significance of the i-th feature: the larger `ro[i]` is, the more likely it is for the i-th feature to be retained.

## Single Coordinate Descent Step

Using the formula above, implement coordinate descent that minimizes the cost function over a single feature i. Note that the intercept (weight 0) is not regularized. The function should accept feature matrix, output, current weights, l1 penalty, and index of feature to optimize over. The function should return new weight for feature i.

In [64]:
def lasso_coordinate_descent_step(i, feature_matrix, output, weights, l1_penalty):
    # compute prediction
    prediction =predict_output(feature_matrix,weights )
    # compute ro[i] = SUM[ [feature_i]*(output - prediction + weight[i]*[feature_i]) ]
    ro_i = sum(feature_matrix[:,i]*(output-prediction+weights[i]*feature_matrix[:,i]))

    if i == 0: # intercept -- do not regularize
        new_weight_i = ro_i 
    elif ro_i < -l1_penalty/2.:
        new_weight_i = ro_i + (l1_penalty/2) 
    elif ro_i > l1_penalty/2.:
        new_weight_i = ro_i - (l1_penalty/2) 
    else:
        new_weight_i = 0.
    
    return new_weight_i

To test the function, run the following cell:

In [65]:
# should print 0.425558846691
import math
print lasso_coordinate_descent_step(1, np.array([[3./math.sqrt(13),1./math.sqrt(10)],[2./math.sqrt(13),3./math.sqrt(10)]]), 
                                   np.array([1., 1.]), np.array([1., 4.]), 0.1)

0.425558846691


## Cyclical coordinate descent 

Now that we have a function that optimizes the cost function over a single coordinate, let us implement cyclical coordinate descent where we optimize coordinates 0, 1, ..., (d-1) in order and repeat.

When do we know to stop? Each time we scan all the coordinates (features) once, we measure the change in weight for each coordinate. If no coordinate changes by more than a specified threshold, we stop.

For each iteration:
1. As you loop over features in order and perform coordinate descent, measure how much each coordinate changes.
2. After the loop, if the maximum change across all coordinates is falls below the tolerance, stop. Otherwise, go back to step 1.

Return weights

**IMPORTANT: when computing a new weight for coordinate i, make sure to incorporate the new weights for coordinates 0, 1, ..., i-1. One good way is to update your weights variable in-place. See following pseudocode for illustration.**
```
for i in range(len(weights)):
    old_weights_i = weights[i] # remember old value of weight[i], as it will be overwritten
    # the following line uses new values for weight[0], weight[1], ..., weight[i-1]
    #     and old values for weight[i], ..., weight[d-1]
    weights[i] = lasso_coordinate_descent_step(i, feature_matrix, output, weights, l1_penalty)
    
    # use old_weights_i to compute change in coordinate
    ...
```

In [67]:
def lasso_cyclical_coordinate_descent(feature_matrix, output, initial_weights, l1_penalty, tolerance):
    weights=initial_weights
    convergence=False
    while convergence== False:
        max_diff=0
        for i in range (len(weights)):
            old_weight= weights[i]
            weights[i]=lasso_coordinate_descent_step(i, feature_matrix, output, weights, l1_penalty)
        
            diff_in_wght=abs(old_weight-weights[i])
            if diff_in_wght>max_diff:
                max_diff=diff_in_wght
        if max_diff< tolerance: # this is the tolerence check
            convergence=True
    return weights
    

Using the following parameters, learn the weights on the sales dataset. 

In [80]:
simple_features=[str(i) for i in range(1,386)]
my_output='386'
initial_weights = np.zeros(len(simple_features)+1)
train_data,test_data=ctscan.random_split(.9,seed=0)

First create a normalized version of the feature matrix, `normalized_simple_feature_matrix`

In [81]:
(simple_feature_matrix, output) = get_numpy_data(train_data, simple_features, my_output)
(normalized_simple_feature_matrix, simple_norms) = normalize_features(simple_feature_matrix) # normalize features

Then, run your implementation of LASSO coordinate descent:

In [85]:
weights = lasso_cyclical_coordinate_descent(normalized_simple_feature_matrix, output,
                                            initial_weights, l1_penalty = 0.0001, tolerance=6)


In [86]:
weights

array([ nan,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   

***QUIZ QUESTIONS***
1. What is the RSS of the learned model on the normalized dataset?
2. Which features had weight zero at convergence?

# Evaluating LASSO fit with more features

Let us split the sales dataset into training and test sets.

In [29]:
train_data,test_data = ctscan.random_split(.8,seed=0)

Let us consider the following set of features.

In [189]:
all_features = ['bedrooms',
                'bathrooms',
                'sqft_living',
                'sqft_lot',
                'floors',
                'waterfront', 
                'view', 
                'condition', 
                'grade',
                'sqft_above',
                'sqft_basement',
                'yr_built', 
                'yr_renovated']



In [30]:
features = [str(i) for i in range(1,386)]

First, create a normalized feature matrix from the TRAINING data with these features.  (Make you store the norms for the normalization, since we'll use them later)

In [36]:
all_feature_matrix, output = get_numpy_data(train_data, features, my_output)
normalized_all_feature_matrix, simple_norms = normalize_features(all_feature_matrix) 
my_output = '386'
initial_weights = np.zeros(len(features)+1)
l1_penalty = 0.001
tolerance = 5.0

First, learn the weights with `l1_penalty=1e7`, on the training data. Initialize weights to all zeros, and set the `tolerance=1`.  Call resulting weights `weights1e7`, you will need them later.

In [52]:
weights1e7 = lasso_cyclical_coordinate_descent(normalized_all_feature_matrix, output,
                                            initial_weights, l1_penalty=0.01, tolerance=5e5)

In [53]:
weights1e7

array([ nan,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   

***QUIZ QUESTION***

What features had non-zero weight in this case?

Next, learn the weights with `l1_penalty=1e8`, on the training data. Initialize weights to all zeros, and set the `tolerance=1`.  Call resulting weights `weights1e8`, you will need them later.

In [46]:
weights1e8 = lasso_cyclical_coordinate_descent(normalized_all_feature_matrix, output,
                                            initial_weights, l1_penalty=0.01,tolerance=0)

weights1e8


KeyboardInterrupt: 

***QUIZ QUESTION***

What features had non-zero weight in this case?

Finally, learn the weights with `l1_penalty=1e4`, on the training data. Initialize weights to all zeros, and set the `tolerance=5e5`.  Call resulting weights `weights1e4`, you will need them later.  (This case will take quite a bit longer to converge than the others above.)

In [194]:
weights1e4 = lasso_cyclical_coordinate_descent(normalized_all_feature_matrix, output,
                                            initial_weights, l1_penalty=1e4, tolerance=5e5)

weights1e4

array([ 77779073.91265011, -22884012.25023269,  15348487.08089937,
        92166869.69883157,  -2139328.08242773,  -8818455.54409456,
         6494209.73310656,   7065162.05053201,   4119079.21006776,
        18436483.52618789, -14566678.54514417,  -5528348.75179453,
       -83591746.20730399,   2784276.46012857])

***QUIZ QUESTION***

What features had non-zero weight in this case?

## Rescaling learned weights

Recall that we normalized our feature matrix, before learning the weights.  To use these weights on a test set, we must normalize the test data in the same way.

Alternatively, we can rescale the learned weights to include the normalization, so we never have to worry about normalizing the test data: 

In this case, we must scale the resulting weights so that we can make predictions with *original* features:
 1. Store the norms of the original features to a vector called `norms`:
```
features, norms = normalize_features(features)
```
 2. Run Lasso on the normalized features and obtain a `weights` vector
 3. Compute the weights for the original features by performing element-wise division, i.e.
```
weights_normalized = weights / norms
```
Now, we can apply `weights_normalized` to the test data, without normalizing it!

Create a normalized version of each of the weights learned above. (`weights1e4`, `weights1e7`, `weights1e8`).

In [205]:
normalized_weights1e7= weights1e7/simple_norms

In [196]:
simple_norms[3]

299962.41868440784

In [208]:
normalized_weights1e4= weights1e4/simple_norms

In [214]:
normalized_weights1e8= weights1e8/simple_norms

In [206]:
print normalized_weights1e7[3]

161.317457472


To check your results, if you call `normalized_weights1e7` the normalized version of `weights1e7`, then:
```
print normalized_weights1e7[3]
```
should return 161.31745624837794.

## Evaluating each of the learned models on the test data

Let's now evaluate the three models on the test data:

In [149]:
(test_feature_matrix, test_output) = get_numpy_data(test_data, all_features, 'price')

In [219]:
def RSS(predicted,data):
    Rss=0
    for i in range(len(predicted)):
        diffn=predicted[i]-data[i]
        Rss+= diffn*diffn
    return (Rss)


Compute the RSS of each of the three normalized weights on the (unnormalized) `test_feature_matrix`:

In [216]:
prediction=predict_output(test_feature_matrix,normalized_weights1e7)
RSS7= RSS(prediction,test_output)
print RSS7

2.75962079198e+14


In [217]:
prediction=predict_output(test_feature_matrix,normalized_weights1e4)
RSS4= RSS(prediction,test_output)


In [218]:
prediction=predict_output(test_feature_matrix,normalized_weights1e8)
RSS8= RSS(prediction,test_output)


In [41]:
model= graphlab.linear_regression.create(ctscan,'386',l1_penalty=0.01)

PROGRESS: Creating a validation set from 5 percent of training data. This may take a while.
          You can set ``validation_set=None`` to disable validation tracking.



WARNING: Detected extremely low variance for feature(s) '6', '7', '17', '18', '29', '30', '39', '61', '71', '88', '89', '98', '99', '100', '125', '136', '157', '158', '167', '181', '191', '220', '247', '255', '256', '262', '263', '264', '271', '287', '295', '296', '304', '328', '334', '335', '336', '340', '341', '342', '343', '349', '350', '353', '359', '367', '368', '375', '376', '383', 'constant' because all entries are nearly the same.
Proceeding with model training using all features. If the model does not provide results of adequate quality, exclude the above mentioned feature(s) from the input dataset.

Linear regression:

--------------------------------------------------------

Number of examples          : 50805

Number of features          : 386

Number of unpacked features : 386

Number of coefficients    : 387

Starting Accelerated Gradient (FISTA)

--------------------------------------------------------

+-----------+----------+-----------+--------------+--------------------+----------------------+---------------+-----------------+

| Iteration | Passes   | Step size | Elapsed Time | Training-max_error | Validation-max_error | Training-rmse | Validation-rmse |

+-----------+----------+-----------+--------------+--------------------+----------------------+---------------+-----------------+

Tuning step size. First iteration could take longer than subsequent iterations.

| 1         | 2        | 0.000000  | 16.645385    | 69.914558          | 69.474321            | 25.778318     | 25.891315       |

| 2         | 3        | 0.000000  | 17.584383    | 66.681967          | 65.818726            | 23.505750     | 23.590507       |

| 3         | 4        | 0.000000  | 18.665260    | 62.890285          | 61.711515            | 21.175162     | 21.221755       |

| 4         | 5        | 0.000000  | 19.701516    | 59.118900          | 57.783279            | 18.982989     | 18.989878       |

| 5         | 6        | 0.000000  | 20.822296    | 55.582914          | 54.254205            | 17.051581     | 17.020125       |

| 6         | 7        | 0.000000  | 21.838658    | 53.121023          | 51.242264            | 15.436849     | 15.372004       |

| 7         | 8        | 0.000000  | 22.899481    | 52.246233          | 48.774042            | 14.146006     | 14.056517       |

| 8         | 9        | 0.000000  | 24.126860    | 51.361465          | 46.811113            | 13.154478     | 13.052261       |

| 9         | 10       | 0.000000  | 25.163905    | 50.395348          | 45.276153            | 12.418766     | 12.317314       |

| 10        | 11       | 0.000000  | 26.200163    | 49.297820          | 44.076139            | 11.886047     | 11.798233       |

+-----------+----------+-----------+--------------+--------------------+----------------------+---------------+-----------------+

TERMINATED: Iteration limit reached.

This model may not be optimal. To improve it, consider increasing `max_iterations`.

In [44]:
model['coefficients']

Columns:
	name	str
	index	str
	value	float
	stderr	float

Rows: 387

Data:
+-------------+-------+-----------------+--------+
|     name    | index |      value      | stderr |
+-------------+-------+-----------------+--------+
| (intercept) |  None |  0.853609648814 |  None  |
|      1      |  None | 0.0138887271088 |  None  |
|      2      |  None |  -3.38723260389 |  None  |
|      3      |  None |  -1.53317742394 |  None  |
|      4      |  None |  -4.73182348921 |  None  |
|      5      |  None |  3.85864621705  |  None  |
|      6      |  None |       0.0       |  None  |
|      7      |  None |       0.0       |  None  |
|      8      |  None |   1.2364619198  |  None  |
|      9      |  None | -0.114346470981 |  None  |
+-------------+-------+-----------------+--------+
[387 rows x 4 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

***QUIZ QUESTION***

Which model performed best on the test data?